# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
# tasks:
#   - name: Install Python 3.11
#     before: |
#       sudo add-apt-repository ppa:deadsnakes/ppa
#       sudo apt update
#       sudo apt install python3.11
#     command: |
#       echo "" >> ~/.bashrc
#       echo "alias python=python3.11" >> ~/.bashrc

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
  extensions:
    - almenon.arepl
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - ms-azuretools.vscode-docker
    - laike9m.cyberbrain